name: UnenchanterRedux
version: 0.0.1
author: Latch
main: Latch.UnenchanterRedux.UnenchanterRedux
api-version: 1.16
softdepend: [Vault]
commands:
  unenchant:
    description: Unenchant
    usage: /unenchant
    permission: ur.command.unenchant